// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcbiBuWoC0dM_2ajCd5y4oGjkyDiUSaKs',
    appId: '1:148895932856:web:99c9c2edb9eebd70c46f4d',
    messagingSenderId: '148895932856',
    projectId: 'habitbot-2556f',
    authDomain: 'habitbot-2556f.firebaseapp.com',
    storageBucket: 'habitbot-2556f.firebasestorage.app',
    measurementId: 'G-H4STEE4PD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYq98rpx-aMj_ktGeEbk_XTDUX0sWxxA0',
    appId: '1:148895932856:android:cce37e90798bcca5c46f4d',
    messagingSenderId: '148895932856',
    projectId: 'habitbot-2556f',
    storageBucket: 'habitbot-2556f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIFeukFPRQgmMFGPMxwMoHWNsmKEYJiBQ',
    appId: '1:148895932856:ios:5377e37210020f57c46f4d',
    messagingSenderId: '148895932856',
    projectId: 'habitbot-2556f',
    storageBucket: 'habitbot-2556f.firebasestorage.app',
    iosBundleId: 'com.example.habitbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIFeukFPRQgmMFGPMxwMoHWNsmKEYJiBQ',
    appId: '1:148895932856:ios:5377e37210020f57c46f4d',
    messagingSenderId: '148895932856',
    projectId: 'habitbot-2556f',
    storageBucket: 'habitbot-2556f.firebasestorage.app',
    iosBundleId: 'com.example.habitbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcbiBuWoC0dM_2ajCd5y4oGjkyDiUSaKs',
    appId: '1:148895932856:web:4805cb98d5dd9bfcc46f4d',
    messagingSenderId: '148895932856',
    projectId: 'habitbot-2556f',
    authDomain: 'habitbot-2556f.firebaseapp.com',
    storageBucket: 'habitbot-2556f.firebasestorage.app',
    measurementId: 'G-GG06K7EGR7',
  );
}
